### PR TITLE
Handle getters returning Optional for nullable fields in toBuilder

### LINKED ISSUE #75: toBuilder doesn't work with nullable field having a getter returning an Optional
This is somehow related to #12 and the handling of Optional. 

The generated code doesn't compile for 
```java
public class Name {
    private String firstName;
    private String lastName;
    private @Nullable String middleName;

    @Builder(style = BuilderStyle.STAGED, toBuilder = "toBuilder")
    Name(String firstName, String lastName, @Nullable String middleName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public Optional<String> getMiddleName() {
        return Optional.ofNullable(this.middleName);
    }
}
```

The generated `toBuilder` method is:
```java
  public static NameBuilder toBuilder(Name name) {
    NameBuilder nameBuilder = new NameBuilder();
    nameBuilder.firstName(name.getFirstName());
    nameBuilder.lastName(name.getLastName());
    nameBuilder.middleName(name.getMiddleName());
    return nameBuilder;
  }
```
and the error is:
> error: incompatible types: Optional<String> cannot be converted to @org.jspecify.annotations.Nullable String
    nameBuilder.middleName(name.getMiddleName());

I would expect the generated code to be:
```java
    nameBuilder.middleName(name.getMiddleName().orElse(null));
```
or
```java
    name.getMiddleName().ifPresent(nameBuilder::middleName);
```

### PR DESCRIPTION
**Pull request by skinny85**
It's a common convention to have fields be stored as nullable values,
but the getters for those field returning a non-`null` `Optional` value -
this way forces consumers of the class to explicitly handle the case when the field is `null`.
However, that becomes a problem when used with Jilt's `toBuilder` feature,
since that assumes the getter and the field have the same type.

Special-case this convention in Jilt's `toBuilder` handling,
and add an `.orElse(null)` invocation to the value returned from the getter
if it returns an `Optional`, but the field is not an `Optional`.
Do this for both classic getters (those that start with `get*()` or `is*()`),
and for record-style getters (whose name is equal to the field name) as well.

Fixes #75

### CODE REVIEW

File: src/main/java/org/jilt/internal/AbstractBuilderGenerator.java
Comment (murdos) [inline src/main/java/org/jilt/internal/AbstractBuilderGenerator.java:264]: Could you also handle this for record-style getter?
```suggestion
                    recordReaderFound = true;
                    // special case: getter that returns Optional<T>,
                    // but the field is of type T
                    if (!attributeIsTypeOpt &&
                            this.typeIsJavaUtilOptional(((ExecutableElement) member).getReturnType())) {
                        onlyGetterOptional = true;
```

File: src/main/java/org/jilt/internal/AbstractBuilderGenerator.java [hunk 1]
```diff
@@ -262,7 +271,7 @@ protected final String accessAttributeOfTargetClass(VariableElement attribute) {
         }
         if (getterFound) {
             // we always prefer the getter if we found one
-            return getterMethod + "()";
+            return getterMethod + "()" + (onlyGetterOptional ? ".orElse(null)" : "");
         } else if (recordReaderFound) {
             // if there's no getter, but there's a record-style read method, use that
             return fieldName + "()";
```
Comment (murdos) [inline src/main/java/org/jilt/internal/AbstractBuilderGenerator.java]: Also required for record-style getter:

```suggestion
            return fieldName + "()" + (onlyGetterOptional ? ".orElse(null)" : "");
```

**Review by murdos — COMMENTED** [review]
Thanks! 

I've tested it locally, and it works for classical getters.
However could you also make it works, as suggested, for record-style getter?

Here's an example:
```java
@Builder(style = BuilderStyle.STAGED, toBuilder = "toBuilder")
public final class Name {
    private final String firstName, lastName;
    private final @Nullable String middleName;

    Name(String firstName, String lastName, @Nullable String middleName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
    }

    public String firstName() {
        return firstName;
    }

    public String lastName() {
        return lastName;
    }

    public Optional<String> middleName() {
        return Optional.ofNullable(middleName);
    }
}
```

**Comment by skinny85** [comment]
Thanks @murdos! I’ll make the change to also handle record-style getters.

**Comment by skinny85** [comment]
I just pushed a change to handle record-style getters, let me know if this is what you had in mind.

**Review by murdos — APPROVED** [review]
Yeah, this is exactly the changes I tested locally :)

**Comment by skinny85** [comment]
I made a small refactoring to handle the edge case if a class has both classic and record-style getters before I merged the PR.

I'll work on a release including these changes this weekend.
