### PR TITLE
Handle Lombok's `@Getter` annotation with `toBuilder`

### LINKED ISSUE #45: toBuilder method support for lombok @Getter
Currently for non record Java classes we are using Lombok annotations e.g. `@RequiredArgsConstructor`, `@Getter`.

Which works fine for generated the Jilt builders, however it doesn't work for the `toBuilder`. 

It doesn't match any of the `elementIsMethodWithoutArgumentsCalled` conditions and results in using the `fieldName`, which fails to compile as the field is private.

```java
package com.singloon;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.jilt.Builder;

@Getter
@RequiredArgsConstructor
@Builder(toBuilder = "toBuilder")
public class LombokGetter {
    private final String name;
    private final int value;
}
```

Error:

```
LombokGetterBuilder.java:20: error: name has private access in LombokGetter
    lombokGetterBuilder.name(lombokGetter.name);
                                         ^
LombokGetterBuilder.java:21: error: value has private access in LombokGetter
    lombokGetterBuilder.value(lombokGetter.value);
                                          ^
2 errors
```

Is there any plans to support this?

### PR DESCRIPTION
**Pull request by skinny85**
Fixes #45

### CODE REVIEW

File: src/main/java/org/jilt/internal/AbstractBuilderGenerator.java [hunk 1]
```diff
@@ -214,23 +215,59 @@ private MethodSpec makeBuildMethod() {
...
+        } else if (packagePrivateFieldFound &&
+                this.determineTargetClassPackage().equals(this.builderClassPackage)) {
+            return fieldName;
+        } else {
+            // It could be that the class uses Lombok,
+            // and the getter hasn't been generated yet.
+            // To handle that case, default to the getter.
+            // Note that Lombok uses the 'is' prefix only for boolean
+            // (not Boolean) properties
+            String setterPrefix = attribute.asType().getKind() == TypeKind.BOOLEAN ? "is" : "get";
```
Comment (thmasker) [inline src/main/java/org/jilt/internal/AbstractBuilderGenerator.java:268]:
```suggestion
            String getterPrefix = attribute.asType().getKind() == TypeKind.BOOLEAN ? "is" : "get";
```

**Review by thmasker — APPROVED** [review]

**Comment by thmasker** [comment]
Nice catch regarding Lombok's `@Value`
